version: '3'

services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  client:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_SCOPE=client
    depends_on:
      - postgres

  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_SCOPE=web
    ports:
      - '3000:3000'

volumes:
  postgres_data:
