// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
} from 'typesafe-i18n';

export type BaseTranslation = BaseTranslationType & DisallowNamespaces;
export type BaseLocale = 'pt-BR';

export type Locales = 'en-US' | 'pt-BR';

export type Translation = RootTranslation & DisallowNamespaces;

export type Translations = RootTranslation & {
  SLASH: NamespaceSLASHTranslation;
};

type RootTranslation = {
  /**
   * V​o​c​ê​ ​t​e​m​ ​c​e​r​t​e​z​a​?
   */
  INQUIRER_CONFIRMATION_QUESTION: string;
  /**
   * S​i​m
   */
  INQUIRER_CONFIRMATION_YES: string;
  /**
   * N​ã​o
   */
  INQUIRER_CONFIRMATION_NO: string;
};

export type NamespaceSLASHTranslation = {
  /**
   * e​x​e​m​p​l​o
   */
  EXAMPLE_NAME: string;
  /**
   * E​x​e​m​p​l​o​ ​d​e​ ​d​e​s​c​r​i​ç​ã​o​.
   */
  EXAMPLE_DESCRIPTION: string;
};

export type Namespaces = 'SLASH';

type DisallowNamespaces = {
  /**
   * reserved for 'SLASH'-namespace\
   * you need to use the `./SLASH/index.ts` file instead
   */
  SLASH?: "[typesafe-i18n] reserved for 'SLASH'-namespace. You need to use the `./SLASH/index.ts` file instead.";
};

export type TranslationFunctions = {
  /**
   * Você tem certeza?
   */
  INQUIRER_CONFIRMATION_QUESTION: () => LocalizedString;
  /**
   * Sim
   */
  INQUIRER_CONFIRMATION_YES: () => LocalizedString;
  /**
   * Não
   */
  INQUIRER_CONFIRMATION_NO: () => LocalizedString;
  SLASH: {
    /**
     * exemplo
     */
    EXAMPLE_NAME: () => LocalizedString;
    /**
     * Exemplo de descrição.
     */
    EXAMPLE_DESCRIPTION: () => LocalizedString;
  };
};

export type Formatters = {};
